### ISSUE TITLE
Registering Name Error

### ISSUE THREAD

**Issue by Nathanwoodburn** [pinheadmz/palmreader#4]
Can't registering a name as it keeps creating an error
<img width="549" alt="image" src="https://user-images.githubusercontent.com/62039630/170628018-858f668f-3ea5-409e-920a-880105a585bd.png">

Also can not register a name without a record as returns an error
<img width="718" alt="image" src="https://user-images.githubusercontent.com/62039630/170628094-bb6e9c8e-27c4-499f-9a66-bb2ac588fbe9.png">

**Comment by pinheadmz** [comment]
empty resource fixed in fixed in https://github.com/pinheadmz/palmreader/commit/9917ee7eb5d51dcfed790d831690c9b0bc02cb7d

the assertion error for the NS I'm not sure, can you pull latest master and try again? (still obviously in alpha, work in progress, regtest only, etc) but i appreciate you banging on it, thanks!

**Comment by Nathanwoodburn** [comment]
Updating a name with a DS causes an error `Invalid DS record. KeyTag must be a uint16`

For example updating a name with the top 2 records works fine, but once I add a DS record is causes the error
![image](https://user-images.githubusercontent.com/62039630/175915296-0961ce47-c2de-4a8b-9337-caa8d74373f8.png)

**Comment by pinheadmz** [comment]
fixed in b8a9464185700b60c8399d8f3ba92cceee22159d
