### ISSUE TITLE
Expire soon names shows open auction names also

### ISSUE THREAD

**Issue by Nathanwoodburn** [pinheadmz/palmreader#6]
The `Expire <100 days` sort option in Names shows the names in auction

![image](https://user-images.githubusercontent.com/62039630/173342172-834d21a2-bfd1-458d-adfa-36279700f2b7.png)

**Comment by pinheadmz** [comment]
I think this is only an issue on regtest, where the `renewalWindow` is only 5000 blocks (which would be, like, a month if blocks were actually 10 minutes apart). I don't think it needs a fix because it is technically true. If you want you can ALSO select `[x] Owned` which DOES filter names by CLOSED state
